# Run task in git bash (can do this in VSCode)

version: "3"
# NOT USED FOR NOW
#dotenv: [.env]

vars:
  PACKAGE_IMPORT_NAME: open_alex_curator
  PYTHON_VERSION: 3.12

tasks:
  create-venv:
    desc: Create a virtual environment
    cmds:
      - uv venv -p {{.PYTHON_VERSION}} .venv
    silent: false

  build:
    desc: Build the project
    cmds:
      - uv build

  sync-dev:
    desc: Sync project dependencies with optionals
    cmds:
      - rm -rf .venv
      - task: create-venv
      - uv sync --extra dev

  sync-test:
    desc: Sync only test dependencies
    cmds:
      - rm -rf .venv
      - task: create-venv
      - uv sync --extra ci

  lint:
    desc: Run pre-commit hooks
    cmds:
      - uv run pre-commit run --all-files

  run-unit-tests:
    cmds:
      - export PYTEST_EXIT_STATUS=0
      - rm -rf test-reports || true
      - uv run pytest ./tests --cov "{{.TASKFILE_DIR}}/src/{{.PACKAGE_IMPORT_NAME}}" --cov-report html --cov-report term  --cov-report xml --junit-xml "{{.TASKFILE_DIR}}/test-reports/report.xml" --cov-fail-under 40 || ((PYTEST_EXIT_STATUS+=$?))
      - mv coverage.xml "{{.TASKFILE_DIR}}/test-reports/" || true
      - mv htmlcov "{{.TASKFILE_DIR}}/test-reports/" && rm -rf htmlcov
      - mv .coverage "{{.TASKFILE_DIR}}/test-reports/" || true
      - exit $PYTEST_EXIT_STATUS
    silent: true
    desc: "Run tests with coverage reports and move results to test-reports directory"

  serve-coverage-report:
    desc: "Serve the coverage report via a local HTTP server on port 8000"
    cmd: |
      echo "Coverage report available at: http://localhost:8000/"
      python -m http.server --directory "{{.TASKFILE_DIR}}/test-reports/htmlcov/" 8000
    silent: false

  clean:
    desc: "Clean up build artifacts, caches, and temporary files"
    cmds:
      - rm -rf dist build coverage.xml test-reports tests/mlruns test-next-best-action
      - find . -type d \( -name "*cache*" -o -name "*.dist-info" -o -name "*.egg-info" -o -name "*htmlcov" \) -not -path "*env/*" -exec rm -r {} + || true
      - find . -type f -name "*.pyc" -not -path "*env/*" -exec rm {} +
    silent: true

  deploy-pipeline-dev:
    desc: Deploy the Databricks pipeline to the dev environment
    cmds:
      - databricks bundle validate && databricks bundle deploy --target dev

  run-data_processing-dev:
    desc: Run the Databricks pipeline in the dev environment
    cmds:
      - databricks bundle run data-pipeline --target dev --no-wait

  help:
    desc: Print all tasks defined in the Taskfile
    cmd: task -l
    silent: true

  default:
    cmds:
      - task: help
    silent: true
